"""create mirrorquant tables

Revision ID: 34c763eaecd4
Revises: 
Create Date: 2026-06-10 14:43:06.731918

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '34c763eaecd4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "heroes",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("notes", sa.Text(), nullable=True),
        sa.Column("start_date", sa.Date(), nullable=False),
        sa.Column("end_date", sa.Date(), nullable=False),
        sa.Column("available_start_date", sa.Date(), nullable=False),
        sa.Column("available_end_date", sa.Date(), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ticker", "start_date", "end_date", name="uq_hero_ticker_window"),
    )
    op.create_index(op.f("ix_heroes_ticker"), "heroes", ["ticker"], unique=False)

    op.create_table(
        "search_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("hero_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=32), nullable=False),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("search_backend", sa.String(length=64), nullable=False),
        sa.Column("hero_regime_code", sa.String(length=64), nullable=False),
        sa.Column("selected_window_json", sa.JSON(), nullable=False),
        sa.Column("effective_window_json", sa.JSON(), nullable=True),
        sa.Column("hero_snapshot_json", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["hero_id"], ["heroes.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_search_runs_hero_id"), "search_runs", ["hero_id"], unique=False)
    op.create_index(op.f("ix_search_runs_mode"), "search_runs", ["mode"], unique=False)

    op.create_table(
        "match_results",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("search_run_id", sa.Integer(), nullable=False),
        sa.Column("rank", sa.Integer(), nullable=False),
        sa.Column("ticker", sa.String(length=16), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("score", sa.Float(), nullable=False),
        sa.Column("regime_label", sa.String(length=255), nullable=False),
        sa.Column("sector", sa.String(length=255), nullable=True),
        sa.Column("explanation", sa.Text(), nullable=False),
        sa.Column("matched_window_json", sa.JSON(), nullable=True),
        sa.Column("features_json", sa.JSON(), nullable=True),
        sa.Column("series_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["search_run_id"], ["search_runs.id"]),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_match_results_search_run_id"), "match_results", ["search_run_id"], unique=False)
    op.create_index(op.f("ix_match_results_ticker"), "match_results", ["ticker"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_match_results_ticker"), table_name="match_results")
    op.drop_index(op.f("ix_match_results_search_run_id"), table_name="match_results")
    op.drop_table("match_results")

    op.drop_index(op.f("ix_search_runs_mode"), table_name="search_runs")
    op.drop_index(op.f("ix_search_runs_hero_id"), table_name="search_runs")
    op.drop_table("search_runs")

    op.drop_index(op.f("ix_heroes_ticker"), table_name="heroes")
    op.drop_table("heroes")
    # ### end Alembic commands ###
