"""add users and hero ownership

Revision ID: bcae4008639a
Revises: 34c763eaecd4
Create Date: 2026-06-13 12:42:39.696170

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcae4008639a'
down_revision: Union[str, Sequence[str], None] = '34c763eaecd4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.add_column('heroes', sa.Column('user_id', sa.Integer(), nullable=True))
    connection = op.get_bind()
    
    result = connection.execute(
        sa.text(
            """
            INSERT INTO users (email, password_hash, created_at)
            VALUES (:email, :password_hash, NOW())
            RETURNING id
            """
        ),
        {
            "email": "local-dev@mirrorquant.app",
            "password_hash": "temporary-dev-password-hash",
        },
    )

    default_user_id = result.scalar_one()

    connection.execute(
        sa.text(
            """
            UPDATE heroes
            SET user_id = :user_id
            """
        ),
        {"user_id": default_user_id},
    )

    op.alter_column('heroes', 'user_id', nullable=False)
    op.drop_constraint(op.f('uq_hero_ticker_window'), 'heroes', type_='unique')
    op.create_index(op.f('ix_heroes_user_id'), 'heroes', ['user_id'], unique=False)
    op.create_unique_constraint('uq_hero_user_ticker_window', 'heroes', ['user_id', 'ticker', 'start_date', 'end_date'])
    op.create_foreign_key(
        'fk_heroes_user_id_users',
        'heroes',
        'users',
        ['user_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_heroes_user_id_users', 'heroes', type_='foreignkey')
    op.drop_constraint('uq_hero_user_ticker_window', 'heroes', type_='unique')
    op.drop_index(op.f('ix_heroes_user_id'), table_name='heroes')
    op.create_unique_constraint(op.f('uq_hero_ticker_window'), 'heroes', ['ticker', 'start_date', 'end_date'], postgresql_nulls_not_distinct=False)
    op.drop_column('heroes', 'user_id')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
